---
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: ajgarciagm-dev
spec:
  selector:
    app: test-bme
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036
