---
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-cm
  namespace: ajgarciagm-dev
data:
  datasource.url: jdbc:mysql://mysql-ocs:3306/products
  datasource.username: ajgarcia
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-dbpass
  namespace: ajgarciagm-dev
type: bootstrap.kubernetes.io/token
stringData:
  datasource.password: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app-secrets
  labels:
    app: products-app-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app-secrets
  template:
    metadata:
      labels:
        app: products-app-secrets
    spec:
      containers:
        - name: java-container
          image: ajgarciaparadigma/test_bme_secrets
          livenessProbe: 
            httpGet: 
              path: /actuator/health
              port: 8080 
              initialDelaySeconds: 40
              periodSeconds: 20
          readnessProbe: 
            httpGet: 
              path: /actuator/health
              port: 8080
              initialDelaySeconds: 60
              periodSeconds: 20
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: spring.profiles.active
              value: oc-secrets
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: project-cm
                  key: datasource.url
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: project-cm
                  key: datasource.username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-dbpass
                  key: datasource.password
---
apiVersion: v1
kind: Service
metadata:
  name: service-product
spec:
  type: NodePort
  selector:
    app: products-app-secrets
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    type: sharded
  name: products-route
  namespace: ajgarciagm-dev
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: service-product

