---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-ocs
  namespace: ajgarciagm-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-ocs
    labels:
       app: mysql-ocs
spec:
    ports:
    - port: 3306
    clusterIP: None
    selector:
      app: mysql-ocs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-ocs
spec:
  selector:
    matchLabels:
      app: mysql-ocs
  serviceName: "mysql-ocs"
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-ocs
    spec:
      volumes:
        - name: mysql-ocs-data
          persistentVolumeClaim:
            claimName: pv-ocs
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-ocs
        image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: products
        - name: MYSQL_USER
          value: ajgarcia
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ocs-data
          mountPath: /var/lib/mysql
