server:
  port: 8080
spring:
  application:
    name: spring-class-exercise
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    show-sql: true
#  jpa:
#    hibernate.ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

# Actuator endpoints configuration
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ info, health, metrics, prometheus ]
  prometheus:
    metrics:
      export:
        enabled: true
